services:
    vue-app:
        build: .
        container_name: vue-spa
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
        command: ['npx', 'vite', 'dev', '--host']
